---
title: 'El Dorado: integrated architecture, urban design, curatorial, education and
  fabrication practice'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:title"
  team:
    title: Team
    output: true
    permalink: "/team/:title"
  uploads:
    title: Uploads
    output: true
  news:
    title: News
    output: true
email: info@eldo.us
description: Established in 1996, el dorado is an integrated architecture, urban design,
  curatorial, education and fabrication practice. We chase big ideas in the middle
  of everywhere.
baseurl: ''
url: eldo2.netlify.app
og_img: "/uploads/art_designfacility-10.jpg"
twitter_username: ''
github_username: ''
addresses:
- address: 510 Avenida Cesar E. Chavez
  phone_number: '816.474.3838'
- address: 1714 NW Overton, 2A
  phone_number: '971.266.8665'