---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: _projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: _team
  label: Team
  create: documents
  match: "**/*"
  templates:
  - team-member
- type: document
  path: _data/news.yaml
  label: News
- type: document
  path: about.md
  label: About
- type: document
  path: index.md
  label: Homepage Slideshow
- type: document
  path: _config.yml
  label: Sitewide Info
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
