# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/img'
collections:
  - name: 'posts'
    label: 'Posts'
    folder: '_posts/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - {label: 'Permalink', name: 'permalink', widget: 'hidden', default: ':title' }
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Image', name: 'image', widget: 'file', allow_multiple: 'false'}
      - {label: "Description", name: "description", widget: "text"}
      - {label: 'Submitted by', name: 'submitted_by', widget: 'string', required: false}
      - label: "Source"
        name: "source"
        widget: "object"
        fields:
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Article Title", name: "title", widget: "string"}
          - {label: "Publication", name: "publication", widget: "string"}
          - {label: "Submitted By", name: "submitted_by", widget: "string", required: false}
      - {label: 'View', name: 'view', widget: 'string'}