---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: layout
  label: layout
  hidden: true
- type: text
  name: title
  label: Title
- name: position
  type: number
  description: ''
  default: 
  required: true
  config:
    min: 
    max: 
    step: 
  label: Order
- name: hero_image
  type: file
  config:
    maxSize: 10
  label: Hero Image
- type: text
  name: short-description
  label: Short Description
- type: textarea
  name: description
  label: Description
- name: images
  type: blocks
  label: Images
  template_types:
  - image
  config:
    min: 
    max: 
- name: images__easier_
  type: image_gallery
  config: {}
  label: Images (easier)
- type: boolean
  name: architecture
  label: Architecture
- type: boolean
  name: curatorial
  label: Curatorial
- type: boolean
  name: urban-design
  label: Urban Design
- type: boolean
  name: education
  label: Education
- type: boolean
  name: fabrication
  label: Fabrication
pages:
- _projects/girl-scout-camp-prairie-schooner.md
- _projects/kansas-city-art-institute-master-plan.md
- _projects/kansas-state-university-architecture-planning-urban-design-regnier-hall-fab-lab-expansion.md
- _projects/market-station.md
- _projects/university-of-tennessee-at-martin-the-garage.md
- _projects/upper-harbor-terminal.md
