---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: layout
  label: layout
  hidden: true
- type: text
  name: title
  label: Title
- type: text
  name: short-description
  label: Short Description
- type: textarea
  name: description
  label: Description
- type: boolean
  name: architecture
  label: Architecture
- type: boolean
  name: curatorial
  label: Curatorial
- type: boolean
  name: urban-design
  label: Urban Design
- type: boolean
  name: education
  label: Education
- type: boolean
  name: fabrication
  label: Fabrication
