---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: layout
  label: layout
  hidden: true
  default: project
- type: text
  name: title
  label: Title
- name: position
  type: number
  description: ''
  default: 
  required: true
  config:
    min: 
    max: 
    step: 
  label: Order
  hidden: true
- name: hero_image
  type: file
  config:
    maxSize: 10
  label: Hero Image
- type: text
  name: short-description
  label: Short Description
- type: textarea
  name: description
  label: Description
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: vimeo_link
  type: text
  config:
    required: false
  label: Vimeo link
  default: https://player.vimeo.com/video/#########
  description: 'Correct format: https://player.vimeo.com/video/#########'
- name: related_projects
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: projects
  label: Related Projects
  description: If left blank, there will be an automatic generated list of projects
    with the same tag
- type: boolean
  name: architecture
  label: Architecture
- type: boolean
  name: curatorial
  label: Artist Collaboration
- type: boolean
  name: urban-design
  label: Urban Design
- type: boolean
  name: education
  label: Education
- type: boolean
  name: fabrication
  label: Fabrication
pages:
- _projects/20th-street-streetscape.md
- _projects/21-ten.md
- _projects/5-delaware.md
- _projects/a-new-home-for-kcur.md
- _projects/albina-vision-community-investment-plan.md
- _projects/alma-pavilion.md
- _projects/aron-levin-residence.md
- _projects/barker-pod.md
- _projects/bhargava-residence.md
- _projects/block-addition-building-visitor-desk.md
- _projects/botwin-building.md
- _projects/boulevard-brewery-co.expansion.md
- _projects/broadway-overpass.md
- _projects/byers-residence.md
- _projects/calgary-uep-public-art-master-plan.md
- _projects/camp-daisy-cabin-prototype.md
- _projects/center-for-spiritual-living.md
- _projects/cortex.md
- _projects/crossroads-hotel-sliding-doors.md
- _projects/destination-medical-center-heart-of-the-city.md
- _projects/digital-labrador.md
- _projects/east-9th-street.md
- _projects/echo-ridge-duplex.md
- _projects/finn-lofts.md
- _projects/girl-scout-camp-prairie-schooner.md
- _projects/grand-boulevard-bridge-redux.md
- _projects/habitat-for-humanity-prototype-house.md
- _projects/hardesty-renaissance-mobile-office.md
- _projects/heritage-park-marina-master-plan.md
- _projects/hodgdon-powder-facility.md
- _projects/holbrook-loft-stair-fabrication.md
- _projects/hughes-residence.md
- _projects/illinois-creek-ranch.md
- _projects/invest-ne.md
- _projects/ipock-residence.md
- _projects/johnson-county-justice-annex.md
- _projects/kansas-city-art-institute-master-plan.md
- _projects/kansas-city-public-television.md
- _projects/kansas-city-vehicle-impound-facility.md
- _projects/kansas-city-vehicle-processing-facility.md
- _projects/kansas-state-university-architecture-planning-urban-design-regnier-hall-fab-lab-expansion.md
- _projects/kennedy-s-bar-grill.md
- _projects/landscaped-edge.md
- _projects/las-virgenes-pure-water-center.md
- _projects/lawrence-residence.md
- _projects/leawood-speculative-office.md
- _projects/limelight.md
- _projects/lone-oaks-farm-phase-i-implementation.md
- _projects/main-street-bridge-redux.md
- _projects/make-it-rain-manheim.md
- _projects/market-station.md
- _projects/mass-timber-mockups.md
- _projects/mattie-rhodes-cultural-center.md
- _projects/mission-peak-capital.md
- _projects/mk12-workstations.md
- _projects/motley-master-plan.md
- _projects/moving-in-moving-out.md
- _projects/national-center-for-drug-free-sport.md
- _projects/neighborworks.md
- _projects/novel-wood-wall.md
- _projects/oak-garage-signage.md
- _projects/park-central-apartments.md
- _projects/parker-loft-stair-fabrication.md
- _projects/paxton-residence.md
- _projects/pedestrian-strands.md
- _projects/pioneer-companies-hq.md
- _projects/pizzabella.md
- _projects/prairie-logic.md
- _projects/roof_ground_water.md
- _projects/shawnee-mission-unitarian-universalist-church.md
- _projects/slender-house.md
- _projects/spay-neuter-kansas-city.md
- _projects/strawberry-hill-housing.md
- _projects/sunset-drive-office-pavilion.md
- _projects/taylor-dining-pavilion.md
- _projects/the-lux.md
- _projects/the-paseo-at-market-station.md
- _projects/theatre-in-the-park.md
- _projects/twa-building.md
- _projects/tyler-loft.md
- _projects/tyler-residence-renovation.md
- _projects/tyler-residence.md
- _projects/unitarian-fellowship-of-lawrence.md
- _projects/university-of-tennessee-at-martin-the-garage.md
- _projects/upper-harbor-terminal.md
- _projects/volland-general-store-fabrication.md
- _projects/volland-house-1.md
- _projects/west-pennway-streetscape.md
- _projects/westside-residence.md
- _projects/willoughby-design-barn.md
