---
label: Project
hide_body: true
display_field: title
fields:
- type: text
  name: layout
  label: layout
  hidden: true
- type: text
  name: title
  label: title
- type: text
  name: short-description
  label: short-description
- type: textarea
  name: description
  label: description
- type: boolean
  name: architecture
  label: architecture
- type: boolean
  name: curatorial
  label: curatorial
- type: boolean
  name: urban-design
  label: urban-design
- type: boolean
  name: education
  label: education
- type: boolean
  name: fabrication
  label: fabrication
